site_name: Ballerina Blog
repo_url: https://github.com/ballerina-platform/blog
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2018 WSO2, Inc.
pages:
- Home: 'index.md'
- Blog: 'blog.md'
- Introducting Native Programming: 'posts/post_0001.md'
- Next geneation integration: 'posts/post_0002.md'
- Quick Tour with Ballerina: 'posts/post_0003.md'
- Thinking in Ballerina: 'posts/post_0004.md'


theme: null
theme_dir: ballerina.io-blog-theme
base_common_resouce_url : 'https://stage.ballerina.io'
markdown_extensions:
 - meta
