site_name: Ballerina Blog
repo_url: https://github.com/ballerina-platform/blog
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2018 WSO2, Inc.
pages:
- Home: 'index.md'
- Introducting Native Programming: 'posts/id-001-thinking-in-ballerina.md'
- Quick Tour with Ballerina: 'posts/id-002-quick-tour with-ballerina.md'
- Next geneation integration: 'posts/id-003-next-geneation-integration.md'
- Thinking in Ballerina: 'posts/id-004-introducting-native-programming.md'
- Post 1 title: 'posts/id-005-post_0001.md'
- Post 2 title: 'posts/id-006-post_0002.md'
- Post 3 title: 'posts/id-007-post_0003.md'
- Post 4 title: 'posts/id-008-post_0004.md'


theme: null
theme_dir: ballerina.io-blog-theme
base_common_resouce_url : 'https://stage.ballerina.io'
markdown_extensions:
 - meta
